#!/bin/bash
# A script that will install and initialise this mod remotely
#
ARMYSTICE_GIT_HOME="${ARMYSTICE_GIT_HOME:-https://github.com/armystice/}"

INIT_SCRIPT_REPO="${ARMYSTICE_GIT_HOME}/mod-bash"
INIT_SCRIPT_URL="${INIT_SCRIPT_REPO}/raw/branch/main/init"
INIT_SCRIPT_PATH="/tmp/armystice-mod-bash.init"

curl -o "${INIT_SCRIPT_PATH}" "${INIT_SCRIPT_URL}"
if [ $? -eq 0 ] && [ -f "${INIT_SCRIPT_PATH}" ]; then
    source "${INIT_SCRIPT_PATH}"
    
    cd "${ARMYSTICE_MOD_HOME}" && git clone "${INIT_SCRIPT_REPO}.git"
    rm "${INIT_SCRIPT_PATH}"
else
    echo "env download failed"
fi