#!/bin/bash
# armystice init scripts should setup the module environment 
# (including environment variables, files and directories)
#
# READ ME!
# init scripts should always be imported/ sourced before working with a module
#
SCRIPT_FILE=$(readlink -f ${BASH_SOURCE[0]})
SCRIPT_DIR=$(dirname ${SCRIPT_FILE})
BASHRC_FILE="${HOME}/.bashrc"

export ARMYSTICE_GIT_HOME="http://vfs1.home3:3000/armystice"
export ARMYSTICE_HOME="${HOME}/.armystice"
export ARMYSTICE_ETC="${ARMYSTICE_HOME}/etc"
export ARMYSTICE_MOD_HOME="${ARMYSTICE_HOME}/mod"
export ARMYSTICE_SHORTCUTS_DIR="${ARMYSTICE_HOME}/shortcuts"

SHORTCUTS_BASHRC="export PATH=\"$\{PATH\}:${ARMYSTICE_SHORTCUTS_DIR}\""
SHORTCUTS_ADDED=$(grep "${SHORTCUTS_BASHRC}" "${BASHRC_FILE}" | wc -l)
if [ "${SHORTCUTS_ADDED}" -lt 1 ]; then
    echo "${SHORTCUTS_BASHRC}" >> "${BASHRC_FILE}" 
fi

mkdir -p "${ARMYSTICE_HOME}"
mkdir -p "${ARMYSTICE_ETC}"
mkdir -p "${ARMYSTICE_MOD_HOME}"

cd "${ARMYSTICE_HOME}"

function log {
    timestamp=$(date -Iseconds)
    script_file="$1"
    level="$2" # info, warn
    message="$3"
    
    echo "${timestamp} ${script_file} ${level}: $3"
}

# Setup!
mkdir -p "${ARMYSTICE_HOME}/mod"